[versions]
agp = "9.1.0"
appcompat = "1.7.1"
guava = "33.5.0-android"
material = "1.13.0"
palette = "1.0.0"
swiperefreshlayout = "1.2.0"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-palette = { module = "androidx.palette:palette", version.ref = "palette" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
material = { module = "com.google.android.material:material", version.ref = "material" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
