config:
  validation: true
  warningsAsErrors: true

complexity:
  LongParameterList:
    ignoreDefaultParameters: true
  TooManyFunctions:
    allowedFunctionsPerClass: 60
    allowedFunctionsPerFile: 15
    allowedFunctionsPerInterface: 50
    ignoreAnnotatedFunctions:
      - Preview

naming:
  FunctionNaming:
    ignoreAnnotated:
      - Composable

style:
  ForbiddenComment:
    active: false

  MagicNumber:
    ignoreCompanionObjectPropertyDeclaration: true
    ignorePropertyDeclaration: true
    ignoreAnnotated:
      - Composable

  UnusedPrivateFunction:
    ignoreAnnotated:
      - Preview
